
services:
  postgres:
    image: postgres:17
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app-db
    ports:
      - 19099:5432
